name: release

on:
  push:
    tags:
      - "v*"

env:
  go_version: "1.21"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go_version }}
          cache: false
      - run: go mod tidy
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
