name: testing

on:
  push:
    branches:
      - "**"

env:
  go_version: "1.21"

jobs:
  vetting:
    name: vetting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          ref: ${{ github.ref }}

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go_version }}

      - name: vetting
        shell: bash
        run: go vet ./...

  linting:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          ref: ${{ github.ref }}

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go_version }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=3m --issues-exit-code=1 ./...
          only-new-issues: true

  unit-tests:
    runs-on: ubuntu-latest
    needs:
      - vetting
      - linting
    env:
      COVER_FILE: coverage.out
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go_version}}
      - run: go mod tidy
      - name: Run unit tests
        run: go test -coverprofile=$COVER_FILE -covermode=atomic ./...
